/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as loanSol from "./Loan.sol";
export { CreditScore__factory } from "./CreditScore__factory";
export { LoanFactory__factory } from "./LoanFactory__factory";
