/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LoanInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "borrower"
      | "creditScore"
      | "durationDays"
      | "factory"
      | "fund"
      | "fundedAt"
      | "getTotalRepayment"
      | "interestRateBps"
      | "lender"
      | "markDefaulted"
      | "principal"
      | "repay"
      | "repaymentDeadline"
      | "status"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LoanDefaulted" | "LoanFunded" | "LoanRepaid"
  ): EventFragment;

  encodeFunctionData(functionFragment: "borrower", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "creditScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "durationDays",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "fund", values?: undefined): string;
  encodeFunctionData(functionFragment: "fundedAt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTotalRepayment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interestRateBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lender", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "markDefaulted",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "principal", values?: undefined): string;
  encodeFunctionData(functionFragment: "repay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "repaymentDeadline",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;

  decodeFunctionResult(functionFragment: "borrower", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creditScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "durationDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundedAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interestRateBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lender", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markDefaulted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "principal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "repaymentDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
}

export namespace LoanDefaultedEvent {
  export type InputTuple = [borrower: AddressLike];
  export type OutputTuple = [borrower: string];
  export interface OutputObject {
    borrower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanFundedEvent {
  export type InputTuple = [lender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [lender: string, amount: bigint];
  export interface OutputObject {
    lender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    borrower: AddressLike,
    principal: BigNumberish,
    interest: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    principal: bigint,
    interest: bigint
  ];
  export interface OutputObject {
    borrower: string;
    principal: bigint;
    interest: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Loan extends BaseContract {
  connect(runner?: ContractRunner | null): Loan;
  waitForDeployment(): Promise<this>;

  interface: LoanInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  borrower: TypedContractMethod<[], [string], "view">;

  creditScore: TypedContractMethod<[], [string], "view">;

  durationDays: TypedContractMethod<[], [bigint], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  fund: TypedContractMethod<[], [void], "payable">;

  fundedAt: TypedContractMethod<[], [bigint], "view">;

  getTotalRepayment: TypedContractMethod<[], [bigint], "view">;

  interestRateBps: TypedContractMethod<[], [bigint], "view">;

  lender: TypedContractMethod<[], [string], "view">;

  markDefaulted: TypedContractMethod<[], [void], "nonpayable">;

  principal: TypedContractMethod<[], [bigint], "view">;

  repay: TypedContractMethod<[], [void], "payable">;

  repaymentDeadline: TypedContractMethod<[], [bigint], "view">;

  status: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "borrower"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "creditScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "durationDays"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "fundedAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalRepayment"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "interestRateBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lender"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "markDefaulted"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "principal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "repaymentDeadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "LoanDefaulted"
  ): TypedContractEvent<
    LoanDefaultedEvent.InputTuple,
    LoanDefaultedEvent.OutputTuple,
    LoanDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "LoanFunded"
  ): TypedContractEvent<
    LoanFundedEvent.InputTuple,
    LoanFundedEvent.OutputTuple,
    LoanFundedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;

  filters: {
    "LoanDefaulted(address)": TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;
    LoanDefaulted: TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;

    "LoanFunded(address,uint256)": TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;
    LoanFunded: TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;

    "LoanRepaid(address,uint256,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
  };
}
