/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICreditScore,
  ICreditScoreInterface,
} from "../../Loan.sol/ICreditScore";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "principal",
        type: "uint256",
      },
    ],
    name: "recordDefault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "principal",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "onTime",
        type: "bool",
      },
    ],
    name: "recordRepayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICreditScore__factory {
  static readonly abi = _abi;
  static createInterface(): ICreditScoreInterface {
    return new Interface(_abi) as ICreditScoreInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICreditScore {
    return new Contract(address, _abi, runner) as unknown as ICreditScore;
  }
}
