/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICreditScore__factory } from "./ICreditScore__factory";
export { Loan__factory } from "./Loan__factory";
