/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CreditScoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_SCORE"
      | "COMPLETED_WEIGHT"
      | "DEFAULT_PENALTY"
      | "ON_TIME_MULTIPLIER"
      | "getScore"
      | "loanFactory"
      | "recordDefault"
      | "recordLoanRequest"
      | "recordRepayment"
      | "records"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BASE_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COMPLETED_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_PENALTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ON_TIME_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "loanFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordDefault",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordLoanRequest",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordRepayment",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "BASE_SCORE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "COMPLETED_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_PENALTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ON_TIME_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "loanFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordLoanRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
}

export interface CreditScore extends BaseContract {
  connect(runner?: ContractRunner | null): CreditScore;
  waitForDeployment(): Promise<this>;

  interface: CreditScoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_SCORE: TypedContractMethod<[], [bigint], "view">;

  COMPLETED_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_PENALTY: TypedContractMethod<[], [bigint], "view">;

  ON_TIME_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  getScore: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  loanFactory: TypedContractMethod<[], [string], "view">;

  recordDefault: TypedContractMethod<
    [user: AddressLike, principal: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordLoanRequest: TypedContractMethod<
    [user: AddressLike, principal: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordRepayment: TypedContractMethod<
    [user: AddressLike, principal: BigNumberish, onTime: boolean],
    [void],
    "nonpayable"
  >;

  records: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalLoans: bigint;
        completedLoans: bigint;
        onTimeRepayments: bigint;
        defaults: bigint;
        totalBorrowed: bigint;
        score: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COMPLETED_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_PENALTY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ON_TIME_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getScore"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "loanFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordDefault"
  ): TypedContractMethod<
    [user: AddressLike, principal: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordLoanRequest"
  ): TypedContractMethod<
    [user: AddressLike, principal: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordRepayment"
  ): TypedContractMethod<
    [user: AddressLike, principal: BigNumberish, onTime: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalLoans: bigint;
        completedLoans: bigint;
        onTimeRepayments: bigint;
        defaults: bigint;
        totalBorrowed: bigint;
        score: bigint;
      }
    ],
    "view"
  >;

  filters: {};
}
