/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "CreditScore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CreditScore__factory>;
    getContractFactory(
      name: "ICreditScore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICreditScore__factory>;
    getContractFactory(
      name: "Loan",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Loan__factory>;
    getContractFactory(
      name: "LoanFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LoanFactory__factory>;

    getContractAt(
      name: "CreditScore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CreditScore>;
    getContractAt(
      name: "ICreditScore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICreditScore>;
    getContractAt(
      name: "Loan",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Loan>;
    getContractAt(
      name: "LoanFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LoanFactory>;

    deployContract(
      name: "CreditScore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CreditScore>;
    deployContract(
      name: "ICreditScore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICreditScore>;
    deployContract(
      name: "Loan",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Loan>;
    deployContract(
      name: "LoanFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LoanFactory>;

    deployContract(
      name: "CreditScore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CreditScore>;
    deployContract(
      name: "ICreditScore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICreditScore>;
    deployContract(
      name: "Loan",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Loan>;
    deployContract(
      name: "LoanFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LoanFactory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
