/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as loanSol from "./Loan.sol";
export type { loanSol };
export type { CreditScore } from "./CreditScore";
export type { LoanFactory } from "./LoanFactory";
export * as factories from "./factories";
export { CreditScore__factory } from "./factories/CreditScore__factory";
export type { ICreditScore } from "./Loan.sol/ICreditScore";
export { ICreditScore__factory } from "./factories/Loan.sol/ICreditScore__factory";
export type { Loan } from "./Loan.sol/Loan";
export { Loan__factory } from "./factories/Loan.sol/Loan__factory";
export { LoanFactory__factory } from "./factories/LoanFactory__factory";
