/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LoanFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createLoan"
      | "creditScore"
      | "getCreditScore"
      | "getLoan"
      | "listLoans"
      | "loanCount"
      | "loans"
      | "markLoanDefaulted"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LoanCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createLoan",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creditScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreditScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "listLoans", values?: undefined): string;
  encodeFunctionData(functionFragment: "loanCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "markLoanDefaulted",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "createLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creditScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreditScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listLoans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loanCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markLoanDefaulted",
    data: BytesLike
  ): Result;
}

export namespace LoanCreatedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    principal: BigNumberish,
    interestRateBps: BigNumberish,
    durationDays: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    principal: bigint,
    interestRateBps: bigint,
    durationDays: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    principal: bigint;
    interestRateBps: bigint;
    durationDays: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LoanFactory extends BaseContract {
  connect(runner?: ContractRunner | null): LoanFactory;
  waitForDeployment(): Promise<this>;

  interface: LoanFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createLoan: TypedContractMethod<
    [
      principal: BigNumberish,
      interestRateBps: BigNumberish,
      durationDays: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  creditScore: TypedContractMethod<[], [string], "view">;

  getCreditScore: TypedContractMethod<[], [string], "view">;

  getLoan: TypedContractMethod<[loanId: BigNumberish], [string], "view">;

  listLoans: TypedContractMethod<[], [string[]], "view">;

  loanCount: TypedContractMethod<[], [bigint], "view">;

  loans: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  markLoanDefaulted: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createLoan"
  ): TypedContractMethod<
    [
      principal: BigNumberish,
      interestRateBps: BigNumberish,
      durationDays: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creditScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCreditScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "listLoans"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "loanCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "markLoanDefaulted"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "LoanCreated"
  ): TypedContractEvent<
    LoanCreatedEvent.InputTuple,
    LoanCreatedEvent.OutputTuple,
    LoanCreatedEvent.OutputObject
  >;

  filters: {
    "LoanCreated(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;
    LoanCreated: TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;
  };
}
